name: Deploy to Tomcat Environments

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment to deploy"
        required: true
        default: "DEV"
        type: choice
        options:
          - DEV
          - TEST
          - PRE_PROD_ENV
          - PROD_ENV

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set environment variables
        run: |
          if [ "${{ github.event.inputs.environment }}" == "DEV" ]; then
            echo "TOMCAT_HOST=${{ secrets.TOMCAT_HOST_DEV }}" >> $GITHUB_ENV
            echo "TOMCAT_USER=${{ secrets.TOMCAT_USER_DEV }}" >> $GITHUB_ENV
            echo "TOMCAT_PASSWORD=${{ secrets.TOMCAT_PASSWORD_DEV }}" >> $GITHUB_ENV
          elif [ "${{ github.event.inputs.environment }}" == "TEST" ]; then
            echo "TOMCAT_HOST=${{ secrets.TOMCAT_HOST_TEST }}" >> $GITHUB_ENV
            echo "TOMCAT_USER=${{ secrets.TOMCAT_USER_TEST }}" >> $GITHUB_ENV
            echo "TOMCAT_PASSWORD=${{ secrets.TOMCAT_PASSWORD_TEST }}" >> $GITHUB_ENV
          elif [ "${{ github.event.inputs.environment }}" == "PRE_PROD_ENV" ]; then
            echo "TOMCAT_HOST=${{ secrets.TOMCAT_HOST_PRE_PROD_ENV }}" >> $GITHUB_ENV
            echo "TOMCAT_USER=${{ secrets.TOMCAT_USER_PRE_PROD_ENV }}" >> $GITHUB_ENV
            echo "TOMCAT_PASSWORD=${{ secrets.TOMCAT_PASSWORD_PRE_PROD_ENV }}" >> $GITHUB_ENV
          elif [ "${{ github.event.inputs.environment }}" == "PROD_ENV" ]; then
            echo "TOMCAT_HOST=${{ secrets.TOMCAT_HOST_PROD_ENV }}" >> $GITHUB_ENV
            echo "TOMCAT_USER=${{ secrets.TOMCAT_USER_PROD_ENV }}" >> $GITHUB_ENV
            echo "TOMCAT_PASSWORD=${{ secrets.TOMCAT_PASSWORD_PROD_ENV }}" >> $GITHUB_ENV
          fi

      - name: Build WAR file
        run: mvn clean package -DskipTests

      - name: Deploy to Apache Tomcat
        run: |
          echo "Deploying to ${{ github.event.inputs.environment }} environment..."
          curl -u ${{ env.TOMCAT_USER }}:${{ env.TOMCAT_PASSWORD }} \
            -T target/*.war \
            "http://${{ env.TOMCAT_HOST }}/manager/text/deploy?path=/myapp&update=true"

      - name: Deployment Success Message
        run: echo "✅ Successfully deployed to ${{ github.event.inputs.environment }}"
