name: Deploy to Apache Tomcat Environments

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Select environment to deploy (DEV, TEST, PRE-PROD, PROD)"
        required: true
        default: "DEV"
        type: choice
        options:
          - DEV
          - TEST
          - PRE-PROD
          - PROD

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build WAR Package
        run: |
          mvn clean package -DskipTests

      - name: Deploy to Selected Environment
        env:
          ENV: ${{ github.event.inputs.environment }}
        run: |
          echo "Deploying application to $ENV environment"

          if [ "$ENV" == "DEV" ]; then
            TOMCAT_SERVER="http://dev-server-ip:8080/manager/text"
          elif [ "$ENV" == "TEST" ]; then
            TOMCAT_SERVER="http://test-server-ip:8080/manager/text"
          elif [ "$ENV" == "PRE-PROD" ]; then
            TOMCAT_SERVER="http://preprod-server-ip:8080/manager/text"
          elif [ "$ENV" == "PROD" ]; then
            TOMCAT_SERVER="http://prod-server-ip:8080/manager/text"
          fi

          echo "Using Tomcat Server: $TOMCAT_SERVER"

          # Deploy WAR using curl
          curl -T target/*.war "$TOMCAT_SERVER/deploy?path=/myapp&update=true" \
            --user ${{ secrets.TOMCAT_USER }}:${{ secrets.TOMCAT_PASSWORD }}

      - name: Deployment Completed
        run: echo "✅ Deployment to ${{ github.event.inputs.environment }} environment successful!"
